import { useEffect, useState } from 'react';

const folderDetails = {
  information: {
    content: <><p className="modal-lead">Hi, I&apos;m Delza Abigail Suryono.</p><img className="information-photo" src="assets/asset6.png" alt="Delza Abigail Suryono" /><p>A Computer Science student specializing in Software Engineering at BINUS University. Beyond technology, I am passionate about creativity, design, teaching, people, and turning ideas into meaningful experiences.</p><div className="detail-grid"><div><span>Education</span><strong>Bina Nusantara University @Bekasi</strong><small>July 2022 - Present</small></div><div><span>Major</span><strong>Computer Science - Software Engineering</strong></div><div><span>GPA</span><strong>3.39</strong></div><div><span>Based in</span><strong>Bogor, Jawa Barat</strong></div></div><div className="social-links" aria-label="Social media links"><a className="social-link" href="https://github.com/abigaildelza-dev" target="_blank" rel="noreferrer" data-label="GitHub" aria-label="GitHub"><img src="assets/vecteezy_a-black-github-icon-in-a-circle_65742280.png" alt="" /></a><a className="social-link" href="https://www.linkedin.com/in/delza-abigail-suryono-897452360/" target="_blank" rel="noreferrer" data-label="LinkedIn" aria-label="LinkedIn"><img src="assets/linkedin-app-icon.png" alt="" /></a><a className="social-link" href="https://discord.com/users/980491156540498001" target="_blank" rel="noreferrer" data-label="Discord" aria-label="Discord"><img src="assets/vecteezy_discord-logo-icon-social-media-icon_23741066.png" alt="" /></a><a className="social-link" href="mailto:abigaildelza12@gmail.com" data-label="Gmail" aria-label="Gmail"><img src="assets/Gmail_Logo_512px.png" alt="" /></a></div></>,
  },
  experience: {
    content: <><p className="modal-lead">Competitions I have participated in.</p><div className="project-list">{[['UI/UX Design Competition HIMPI', 'Participated as part of the NEXA team, contributing ideas, UI/UX design, and visual development.', <><img src="assets/Sertif.jfif" alt="Sertifikat UI/UX Design Competition HIMPI" /><img src="assets/experience/himpi.jpeg" alt="Dokumentasi UI/UX Design Competition HIMPI" /></>], ['Techfest 2025 UI/UX Competition', 'Participated as part of the Aizette team, contributing ideas and UI/UX design for an adaptive learning platform.', <video controls preload="metadata" aria-label="Video dokumentasi Techfest 2025 UI/UX Competition"><source src="assets/experience/aizette.mp4" type="video/mp4" />Browser kamu tidak mendukung pemutaran video.</video>]].map(([name, text, media]) => <article key={name}><span>{name}</span><p>{text}</p><div className="competition-media">{media}</div></article>)}</div></>,
  },
  journey: {
    content: <><p className="modal-lead">Building experiences also means building communities.</p><div className="timeline">{[['2025 - 2026', 'Seni Tari Mahasiswa Bina Nusantara', 'Vice Head of Event Division, Human Resources Development Coordinator, Head of Event Division, and Project Manager for STAMANARA programs.', 'stam.jfif'], ['2025 - 2026', 'Freshmen Chaperone BINUS', 'Freshman Leader and Freshman Partner, guiding students through orientation, campus life, academic systems, and BINUS culture.', 'freshmenchaperone.jfif'], ['2026 - Present', 'Ruangguru English Academy', 'English teacher for kindergarten to adult learners, including IELTS preparation, adapting lessons to different needs and learning styles.'], ['2024', 'Parents Day 2024 Volunteer', 'Served in the Entrance and Department Mobilization Division, ensuring a seamless event experience for incoming students and their families. I managed crowd flow across the venue, guided guests to designated seating, and directed attendees to their respective department sessions to keep the schedule running smoothly.', 'parentsday.jfif'], ['Volunteer', 'Teacher Volunteer TFI', 'Had the rewarding experience of serving as a Volunteer Teacher, working directly with primary school students to build their foundational skills in Mathematics and English! Through interactive lessons and dedicated mentoring', 'tfi.jfif']].map(([date, name, text, image]) => <article key={name}><time>{date}</time><div><strong>{name}</strong><p>{text}</p>{image && <img src={`assets/${image}`} alt={`Dokumentasi ${name}`} />}</div></article>)}</div></>,
  },
  skills: {
    content: <><p className="modal-lead">A mix of design, technology, communication, and creative problem solving.</p><div className="skill-groups"><div><span>Design</span><p>UI/UX Design, Prototyping, Design Thinking, Product Ideation, Visual Development</p></div><div className="technology-group"><span>Technology</span><div className="tech-icons" aria-label="Technology skills">{[['HTML5.png', 'HTML5'], ['CSS3.png', 'CSS3'], ['Figma.png', 'Figma'], ['copilot-icon.png', 'GitHub Copilot'], ['office-365-icon.png', 'Microsoft Office 365'], ['canva-icon.png', 'Canva'], ['google-docs-icon.png', 'Google Docs'], ['icons8-cisco-packet-tracer-100.png', 'Cisco Packet Tracer']].map(([src, label]) => <span className="tech-icon" tabIndex="0" data-label={label} key={label}><img src={`assets/${src}`} alt={label} /></span>)}</div></div><div><span>People</span><p>Leadership, project management, time management, collaboration, presentation, adaptability, critical thinking</p></div><div><span>Language</span><p>Indonesian (Native), English (Intermediate), Mandarin (Elementary)</p></div></div></>,
  },
};

const folders = [['skills', 'folder4last2.png', 'My Skill', 'about'], ['journey', 'folder3last2.png', 'Journey', 'work'], ['experience', 'folder2last2.png', 'Experience', 'notes'], ['information', 'folder1last2.png', 'Information', 'contact']];

export default function ConnectPage({ onBack, onProjects }) {
  const [active, setActive] = useState(null);
  const detail = active ? folderDetails[active.key] : null;
  useEffect(() => { document.body.classList.toggle('modal-open', Boolean(active)); return () => document.body.classList.remove('modal-open'); }, [active]);
  useEffect(() => { const close = (event) => event.key === 'Escape' && setActive(null); document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, []);

  return <><main className="folder-page"><div className="background" aria-hidden="true" /><div className="shade" aria-hidden="true" /><div className="grain" aria-hidden="true" />
    <button className="back-link" type="button" onClick={onBack} aria-label="Kembali ke portfolio utama"><span aria-hidden="true">←</span> back</button>
    <section className="folder-picker" aria-labelledby="folder-title"><p className="eyebrow">A little more to explore</p><h1 id="folder-title">Choose a folder</h1><button className="projects-link" type="button" onClick={onProjects}>See my projects? <span aria-hidden="true">↗</span></button><div className="folder-stack" aria-label="Pilihan folder portfolio">{folders.map(([key, src, alt, label], index) => <button className={`folder folder--${['one', 'two', 'three', 'four'][index]}${active?.key === key ? ' is-selected' : ''}`} type="button" onClick={() => setActive({ key, src })} aria-label={`Buka folder ${alt}`} key={key}><img src={`assets/${src}`} alt={alt} /><span>{label}</span></button>)}</div></section>
  </main>{active && <div className={`modal is-visible theme-${active.key}`}><div className="modal-backdrop" onClick={() => setActive(null)} /><section className="modal-panel" role="dialog" aria-modal="true" aria-labelledby="modal-title" tabIndex="-1"><img className="modal-folder-art" src={`assets/${active.src}`} alt={`${detail.title} folder`} /><button className="modal-close" type="button" onClick={() => setActive(null)} aria-label="Tutup folder">×</button><p className="modal-kicker">{detail.kicker}</p><h2 id="modal-title">{detail.title}</h2><div className="modal-content">{detail.content}</div></section></div>}</>;
}
